#!/bin/bash
#BSUB -J HPC-Project
#BSUB -q debug
#BSUB -n 10
#BSUB -e %J-petsc.err
#BSUB -o %J-petsc.out

module purge
module load intel/2018.4
module load mpi/intel/2018.4

# mpirun -np 10 ./main.out
mpirun -np 10 ./main.out PETSC_TRUE