#!/bin/bash
#BSUB -J HPC-Project
#BSUB -q ser
#BSUB -n 5
#BSUB -e %J-petsc.err
#BSUB -o %J-petsc.out
#BSUB -m 'r01n15'

module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun -np 5 ./main.out -n 100 -dt=0.00001 -restart=PETSC_FALSE
# mpirun -np 10 ./main.out -n 100 -dt=0.00001 -restart=false -log_view > Project.log 2>&1