#!/bin/bash
#BSUB -J HPC-Project-Valgrind
#BSUB -q debug
#BSUB -n 1
#BSUB -e %J-petsc.err
#BSUB -o %J-petsc.out

module purge
module load intel/2018.4
module load mpi/intel/2018.4
module load valgrind/3.14.0

valgrind --leak-check=full ./main.out 
# mpirun -np 10 ./main.out PETSC_TRUE
# mpirun -np 10 ./main.out -log_view > Project.log 2>&1